version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # open-pull-requests-limit: 0
    reviewers:
      - "yuokada"
  - package-ecosystem: "pip"
    directory: "ansible/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "yuokada"
