version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # open-pull-requests-limit: 0
    reviewers:
      - "yuokada"
  - package-ecosystem: "pip"
    directory: "ansible/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]    
    reviewers:
      - "yuokada"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "yuokada"
