version: '3'

# see: https://docs.docker.jp/compose/overview.html
# see: https://docs.docker.jp/compose/compose-file.html
services:
  web:
    working_dir: /var/www/bms
    build:
      context: ./web
      dockerfile: Dockerfile.legacy
    ports:
    - "8888:80"
    volumes:
    # - .:/code
    - ./web/ga:/var/www/bms/fuel/app/config/test
    links:
    - mysql_server
  # nginx:
  #   image: nginx:1.19
  #   volumes:
  #   - ./templates:/etc/nginx/templates
  #   ports:
  #   - "8080:80"
  #   environment:
  #   - NGINX_HOST=b-ms.info
  #   - NGINX_PORT=80
  # redis:
  #   image: redis:6.0-buster
  mysql_server:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'bms'
      MYSQL_USER: 'apiuser'
      MYSQL_PASSWORD: 'password'
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - "3306:3306"
# volumes:
#   logvolume01: {}
