---
- name: Create directories for aws
  file:
    path: /home/ubuntu/.aws
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755
    recurse: yes

- name: Create credential file for aws
  template:
    src: aws_config.j2
    dest: /home/ubuntu/.aws/config
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Get password for AWS ecr
  shell: aws ecr get-login-password --region ap-northeast-1
  become: true
  become_user: ubuntu
  become_method: sudo
  register: ecr_password
# - debug:
#     var: ecr_password.stdout
  tags:
    - ecr

- name: docker login to ecr
  # see: https://docs.ansible.com/ansible/latest/collections/community/general/docker_login_module.html
  community.general.docker_login:
      registry_url: 949140100595.dkr.ecr.ap-northeast-1.amazonaws.com
      username: AWS
      password: "{{ ecr_password.stdout }}"
      reauthorize: yes
  tags:
    - ecr
