on:
  push:
  pull_request:

name: Dockerfile validation

jobs:
  docker_validate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # see: https://github.com/hadolint/hadolint#configure
      # see: https://hub.docker.com/r/hadolint/hadolint
      # see: https://github.com/marketplace/actions/hadolint-action
      - uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: ./docker/web/Dockerfile

      - uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: ./docker/web/Dockerfile.legacy

      - uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: ./docker/heroku/Dockerfile.heroku
