on:
  push:
  pull_request:

name: Dockerfile validation

jobs:
  docker_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # see: https://github.com/hadolint/hadolint#configure
      # see: https://hub.docker.com/r/hadolint/hadolint
      # see: https://github.com/marketplace/actions/hadolint-action
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ./docker/web/Dockerfile

      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ./docker/web/Dockerfile.legacy

      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ./docker/heroku/Dockerfile.heroku
